jwt:
  private:
    key: classpath:app.key
  public:
    key: classpath:app.pub

spring:
  application:
    name: pouch
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/gamepouchdb
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver
